alibaba/jvm-sandbox

- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/server/jetty/servlet/ModuleHttpServlet.java
提交，增加jvm-sandbox容器http路由支持模糊匹配功能
> 增加HTTP路由支持模糊匹配功能

- sandbox-agent/src/main/java/com/alibaba/jvm/sandbox/agent/AgentLauncher.java
> fix compile error

- bin/sandbox-logback.xml
> sandbox.log时区问题

- pom.xml
- sandbox-core/pom.xml
- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/CoreLauncher.java
CoreLauncher 的 attachAgent() 不使用反射代码
> CoreLauncher 代码优化

- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/classloader/ModuleClassLoader.java
- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/util/FileUtils.java
https://github.com/alibaba/jvm-sandbox/issues/75
> 解决docker环境下java.io.tmpdir可能不存在的问题

- sandbox-common-api/src/main/java/com/alibaba/jvm/sandbox/api/routing/RoutingExt.java
- sandbox-common-api/src/main/java/com/alibaba/jvm/sandbox/api/routing/RoutingInfo.java
- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/classloader/ModuleClassLoader.java
- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/manager/impl/DefaultConfigInfo.java
- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/manager/impl/DefaultCoreModuleManager.java
- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/manager/impl/ModuleJarLoader.java
> 开放模块指定类加载器路由能力

- bin/sandbox-packages.sh
- bin/sandbox.sh
- sandbox-agent/src/main/java/com/alibaba/jvm/sandbox/agent/AgentLauncher.java
- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/CoreConfigure.java
- sandbox-debug-module/src/main/java/com/alibaba/jvm/sandbox/module/debug/DebugLifeCycleModule.java
- sandbox-debug-module/src/main/java/com/alibaba/jvm/sandbox/module/debug/LogServletAccessModule.java
在sandbox主目录下，新增一个用户用户模块sandbox-module目录，sandbox在启动时，自动查找该目录加载用户模块
> add default user module dir {SANDBOX_HOME_DIR}/sandbox-module/

- sandbox-api/src/main/java/com/alibaba/jvm/sandbox/api/ModuleLifecycleAdapter.java
- sandbox-api/src/main/java/com/alibaba/jvm/sandbox/api/listener/ext/AdviceAdapterListener.java
- sandbox-api/src/main/java/com/alibaba/jvm/sandbox/api/listener/ext/AdviceListener.java
- sandbox-api/src/main/java/com/alibaba/jvm/sandbox/api/listener/ext/Behavior.java
- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/server/jetty/servlet/ModuleHttpServlet.java
- sandbox-core/src/test/java/com/alibaba/jvm/sandbox/qatest/core/enhance/listener/TracingAdviceListener.java
- sandbox-debug-module/src/main/java/com/alibaba/jvm/sandbox/module/debug/util/InterfaceProxyUtils.java
1. 添加生命周期适配器让用户选择实现指定生命周期方法;
2. Command和Http路径兼容路径/前缀;
3. 添加后置事件，无论方法正常返回还是抛出异常都执行;
> 一些提升开发体验的优化

- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/server/jetty/JettyCoreServer.java
> 修复应用启动失败后，进程无法正常退出

- bin/sandbox.sh
fix #184: support attach jvm starting by diff user
> fix #184: support attach jvm starting by diff user

- sandbox-api/src/test/java/com/alibaba/jvm/sandbox/api/util/GaStringUtilsTests.java
I've analysed your codebase and noticed that `com.alibaba.jvm.sandbox.api.util.GaStringUtils` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.
> Add unit tests for com.alibaba.jvm.sandbox.api.util.GaStringUtils

- bin/sandbox.sh
- sandbox-agent/src/main/java/com/alibaba/jvm/sandbox/agent/AgentLauncher.java
tested on window 10 with [git](https://git-scm.com/download/win)
need add %GIT_HOME%\bin;%GIT_HOME%\usr\bin;%GIT_HOME%\cmd;%GIT_HOME%\mingw64\bin to PATH
then run with sh:`sh ./bin/sandbox.sh -p $PID`
> support windows with linux shell (ie:mingw or cygwin )

- sandbox-agent/src/main/java/com/alibaba/jvm/sandbox/agent/SandboxClassLoader.java
优化了调用URLClassLoader.close()方式，修复了反射获取private变量时没有setAccessible(true)bug。
> 修改URLClassLoader关闭jar资源引用bug

- .gitignore
- sandbox-core/src/test/java/com/alibaba/jvm/sandbox/qatest/core/enhance/target/Computer.java
- sandbox-core/src/test/java/com/alibaba/jvm/sandbox/qatest/core/enhance/target/InheritedComputer.java
> 补充enhance/target

- .gitignore
- .travis.yml
- README.md
- pom.xml
- sandbox-core/pom.xml
- sandbox-core/src/test/java/com/alibaba/jvm/sandbox/qatest/core/enhance/CalculatorImplByAdviceListenerTestCase.java
- sandbox-core/src/test/java/com/alibaba/jvm/sandbox/qatest/core/enhance/CalculatorImplByEventListenerTestCase.java
- sandbox-core/src/test/java/com/alibaba/jvm/sandbox/qatest/core/enhance/ICalculatorTestCase.java
- sandbox-core/src/test/java/com/alibaba/jvm/sandbox/qatest/core/enhance/target/Calculator.java
- sandbox-core/src/test/java/com/alibaba/jvm/sandbox/qatest/core/util/CalculatorHelper.java
- sandbox-debug-module/pom.xml
- sandbox-module-starter/pom.xml
本PR提交内容涉及如下信息变更
- .gitignore优化，排除掉core/enhance/target源码文件
- 添加静态方法相关调用用例，包含通过类实例调用调用静态方法以及类本身调用静态方法两种场景
> 添加静态方法调用相关测试用例

- .gitignore
- sandbox-core/src/test/java/com/alibaba/jvm/sandbox/qatest/core/enhance/target/Computer.java
- sandbox-core/src/test/java/com/alibaba/jvm/sandbox/qatest/core/enhance/target/InheritedComputer.java
Reverts alibaba/jvm-sandbox#239
> Revert "补充enhance/target"

- .gitignore
- sandbox-core/src/test/java/com/alibaba/jvm/sandbox/qatest/core/enhance/target/Computer.java
- sandbox-core/src/test/java/com/alibaba/jvm/sandbox/qatest/core/enhance/target/InheritedComputer.java
Reverts alibaba/jvm-sandbox#240
> Revert "Revert "补充enhance/target""

- pom.xml
- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/classloader/BusinessClassLoaderHolder.java
- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/classloader/RoutingURLClassLoader.java
- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/enhance/weaver/EventListenerHandler.java
- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/util/AsmUtils.java
- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/util/SandboxClassUtils.java
> Develop for 20200115 issue 260

- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/manager/impl/DefaultModuleEventWatcher.java
SandboxClassFileTransformer 需要无条件注入Instrumentation
> 修改SandboxClassFileTransformer需要add的时机,修复Agent模式类增强失效

- doc/JVM-SANDBOX-DEVELOPER-GUIDE-Chinese.md
- doc/JVM-SANDBOX-DEVELOPER-GUIDE-English.md
The below image may not be the author want.
Fix the markdown syntax
> fix markdown syntax error

- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/enhance/weaver/SingleEventFactory.java
> fix throwable 字打错了

- sandbox-mgr-module/src/main/java/com/alibaba/jvm/sandbox/module/mgr/ModuleMgrModule.java
add command list info to  module manager detail
> feature: add module manager commands detail info

- sandbox-core/src/main/java/com/alibaba/jvm/sandbox/core/util/matcher/structure/ClassStructureImplByAsm.java
> fix for #385
